train_file: 'data/text_location.jsonl'
gis_bert_config: 'resources/gis_config.json'

embed_dim: 256
batch_size: 256
mlm_probability: 0.15

optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-4, epochs: 30, min_lr: 1e-5, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 20, cooldown_epochs: 0}







